//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeInDiary.Main.SettingsFile {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class HomeSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HomeSettings defaultInstance = ((HomeSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HomeSettings())));
        
        public static HomeSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string HomeScreenStyle {
            get {
                return ((string)(this["HomeScreenStyle"]));
            }
            set {
                this["HomeScreenStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bottom")]
        public string NavbarPosition {
            get {
                return ((string)(this["NavbarPosition"]));
            }
            set {
                this["NavbarPosition"] = value;
            }
        }
    }
}
